# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modelservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modelservice.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12modelservice.proto\"\x14\n\x12\x42uildModelsRequest\"\x15\n\x13\x42uildModelsResponse\"6\n\x0fGetModelRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x11\n\tgis_joins\x18\x02 \x01(\t\"D\n\x10GetModelResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"f\n\x19WorkerRegistrationRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12)\n\x0flocal_gis_joins\x18\x03 \x03(\x0b\x32\x10.GisJoinMetadata\"#\n\x0fGisJoinMetadata\x12\x10\n\x08gis_join\x18\x01 \x01(\t\"-\n\x1aWorkerRegistrationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x94\x02\n\x06Master\x12:\n\x0b\x42uildModels\x12\x13.BuildModelsRequest\x1a\x14.BuildModelsResponse\"\x00\x12\x32\n\tGetModels\x12\x10.GetModelRequest\x1a\x11.GetModelResponse\"\x00\x12K\n\x0eRegisterWorker\x12\x1a.WorkerRegistrationRequest\x1a\x1b.WorkerRegistrationResponse\"\x00\x12M\n\x10\x44\x65registerWorker\x12\x1a.WorkerRegistrationRequest\x1a\x1b.WorkerRegistrationResponse\"\x00\x32x\n\x06Worker\x12:\n\x0b\x42uildModels\x12\x13.BuildModelsRequest\x1a\x14.BuildModelsResponse\"\x00\x12\x32\n\tGetModels\x12\x10.GetModelRequest\x1a\x11.GetModelResponse\"\x00\x62\x06proto3'
)




_BUILDMODELSREQUEST = _descriptor.Descriptor(
  name='BuildModelsRequest',
  full_name='BuildModelsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=42,
)


_BUILDMODELSRESPONSE = _descriptor.Descriptor(
  name='BuildModelsResponse',
  full_name='BuildModelsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=65,
)


_GETMODELREQUEST = _descriptor.Descriptor(
  name='GetModelRequest',
  full_name='GetModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_id', full_name='GetModelRequest.model_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gis_joins', full_name='GetModelRequest.gis_joins', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=121,
)


_GETMODELRESPONSE = _descriptor.Descriptor(
  name='GetModelResponse',
  full_name='GetModelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_id', full_name='GetModelResponse.model_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filename', full_name='GetModelResponse.filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='GetModelResponse.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=191,
)


_WORKERREGISTRATIONREQUEST = _descriptor.Descriptor(
  name='WorkerRegistrationRequest',
  full_name='WorkerRegistrationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='WorkerRegistrationRequest.hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='WorkerRegistrationRequest.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='local_gis_joins', full_name='WorkerRegistrationRequest.local_gis_joins', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=295,
)


_GISJOINMETADATA = _descriptor.Descriptor(
  name='GisJoinMetadata',
  full_name='GisJoinMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gis_join', full_name='GisJoinMetadata.gis_join', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=332,
)


_WORKERREGISTRATIONRESPONSE = _descriptor.Descriptor(
  name='WorkerRegistrationResponse',
  full_name='WorkerRegistrationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='WorkerRegistrationResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=379,
)

_WORKERREGISTRATIONREQUEST.fields_by_name['local_gis_joins'].message_type = _GISJOINMETADATA
DESCRIPTOR.message_types_by_name['BuildModelsRequest'] = _BUILDMODELSREQUEST
DESCRIPTOR.message_types_by_name['BuildModelsResponse'] = _BUILDMODELSRESPONSE
DESCRIPTOR.message_types_by_name['GetModelRequest'] = _GETMODELREQUEST
DESCRIPTOR.message_types_by_name['GetModelResponse'] = _GETMODELRESPONSE
DESCRIPTOR.message_types_by_name['WorkerRegistrationRequest'] = _WORKERREGISTRATIONREQUEST
DESCRIPTOR.message_types_by_name['GisJoinMetadata'] = _GISJOINMETADATA
DESCRIPTOR.message_types_by_name['WorkerRegistrationResponse'] = _WORKERREGISTRATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuildModelsRequest = _reflection.GeneratedProtocolMessageType('BuildModelsRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUILDMODELSREQUEST,
  '__module__' : 'modelservice_pb2'
  # @@protoc_insertion_point(class_scope:BuildModelsRequest)
  })
_sym_db.RegisterMessage(BuildModelsRequest)

BuildModelsResponse = _reflection.GeneratedProtocolMessageType('BuildModelsResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUILDMODELSRESPONSE,
  '__module__' : 'modelservice_pb2'
  # @@protoc_insertion_point(class_scope:BuildModelsResponse)
  })
_sym_db.RegisterMessage(BuildModelsResponse)

GetModelRequest = _reflection.GeneratedProtocolMessageType('GetModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMODELREQUEST,
  '__module__' : 'modelservice_pb2'
  # @@protoc_insertion_point(class_scope:GetModelRequest)
  })
_sym_db.RegisterMessage(GetModelRequest)

GetModelResponse = _reflection.GeneratedProtocolMessageType('GetModelResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETMODELRESPONSE,
  '__module__' : 'modelservice_pb2'
  # @@protoc_insertion_point(class_scope:GetModelResponse)
  })
_sym_db.RegisterMessage(GetModelResponse)

WorkerRegistrationRequest = _reflection.GeneratedProtocolMessageType('WorkerRegistrationRequest', (_message.Message,), {
  'DESCRIPTOR' : _WORKERREGISTRATIONREQUEST,
  '__module__' : 'modelservice_pb2'
  # @@protoc_insertion_point(class_scope:WorkerRegistrationRequest)
  })
_sym_db.RegisterMessage(WorkerRegistrationRequest)

GisJoinMetadata = _reflection.GeneratedProtocolMessageType('GisJoinMetadata', (_message.Message,), {
  'DESCRIPTOR' : _GISJOINMETADATA,
  '__module__' : 'modelservice_pb2'
  # @@protoc_insertion_point(class_scope:GisJoinMetadata)
  })
_sym_db.RegisterMessage(GisJoinMetadata)

WorkerRegistrationResponse = _reflection.GeneratedProtocolMessageType('WorkerRegistrationResponse', (_message.Message,), {
  'DESCRIPTOR' : _WORKERREGISTRATIONRESPONSE,
  '__module__' : 'modelservice_pb2'
  # @@protoc_insertion_point(class_scope:WorkerRegistrationResponse)
  })
_sym_db.RegisterMessage(WorkerRegistrationResponse)



_MASTER = _descriptor.ServiceDescriptor(
  name='Master',
  full_name='Master',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=382,
  serialized_end=658,
  methods=[
  _descriptor.MethodDescriptor(
    name='BuildModels',
    full_name='Master.BuildModels',
    index=0,
    containing_service=None,
    input_type=_BUILDMODELSREQUEST,
    output_type=_BUILDMODELSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetModels',
    full_name='Master.GetModels',
    index=1,
    containing_service=None,
    input_type=_GETMODELREQUEST,
    output_type=_GETMODELRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterWorker',
    full_name='Master.RegisterWorker',
    index=2,
    containing_service=None,
    input_type=_WORKERREGISTRATIONREQUEST,
    output_type=_WORKERREGISTRATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeregisterWorker',
    full_name='Master.DeregisterWorker',
    index=3,
    containing_service=None,
    input_type=_WORKERREGISTRATIONREQUEST,
    output_type=_WORKERREGISTRATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTER)

DESCRIPTOR.services_by_name['Master'] = _MASTER


_WORKER = _descriptor.ServiceDescriptor(
  name='Worker',
  full_name='Worker',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=660,
  serialized_end=780,
  methods=[
  _descriptor.MethodDescriptor(
    name='BuildModels',
    full_name='Worker.BuildModels',
    index=0,
    containing_service=None,
    input_type=_BUILDMODELSREQUEST,
    output_type=_BUILDMODELSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetModels',
    full_name='Worker.GetModels',
    index=1,
    containing_service=None,
    input_type=_GETMODELREQUEST,
    output_type=_GETMODELRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKER)

DESCRIPTOR.services_by_name['Worker'] = _WORKER

# @@protoc_insertion_point(module_scope)
