# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modelservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modelservice.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12modelservice.proto\"\x14\n\x12\x42uildModelsRequest\"\x15\n\x13\x42uildModelsResponse\"\x12\n\x10GetModelsRequest\"\x13\n\x11GetModelsResponse\"\x1b\n\x19WorkerRegistrationRequest\"\x1c\n\x1aWorkerRegistrationResponse2\x96\x02\n\x06Master\x12:\n\x0b\x42uildModels\x12\x13.BuildModelsRequest\x1a\x14.BuildModelsResponse\"\x00\x12\x34\n\tGetModels\x12\x11.GetModelsRequest\x1a\x12.GetModelsResponse\"\x00\x12K\n\x0eRegisterWorker\x12\x1a.WorkerRegistrationRequest\x1a\x1b.WorkerRegistrationResponse\"\x00\x12M\n\x10\x44\x65registerWorker\x12\x1a.WorkerRegistrationRequest\x1a\x1b.WorkerRegistrationResponse\"\x00\x32z\n\x06Worker\x12:\n\x0b\x42uildModels\x12\x13.BuildModelsRequest\x1a\x14.BuildModelsResponse\"\x00\x12\x34\n\tGetModels\x12\x11.GetModelsRequest\x1a\x12.GetModelsResponse\"\x00\x62\x06proto3'
)




_BUILDMODELSREQUEST = _descriptor.Descriptor(
  name='BuildModelsRequest',
  full_name='BuildModelsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=42,
)


_BUILDMODELSRESPONSE = _descriptor.Descriptor(
  name='BuildModelsResponse',
  full_name='BuildModelsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=65,
)


_GETMODELSREQUEST = _descriptor.Descriptor(
  name='GetModelsRequest',
  full_name='GetModelsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=85,
)


_GETMODELSRESPONSE = _descriptor.Descriptor(
  name='GetModelsResponse',
  full_name='GetModelsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=106,
)


_WORKERREGISTRATIONREQUEST = _descriptor.Descriptor(
  name='WorkerRegistrationRequest',
  full_name='WorkerRegistrationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=135,
)


_WORKERREGISTRATIONRESPONSE = _descriptor.Descriptor(
  name='WorkerRegistrationResponse',
  full_name='WorkerRegistrationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['BuildModelsRequest'] = _BUILDMODELSREQUEST
DESCRIPTOR.message_types_by_name['BuildModelsResponse'] = _BUILDMODELSRESPONSE
DESCRIPTOR.message_types_by_name['GetModelsRequest'] = _GETMODELSREQUEST
DESCRIPTOR.message_types_by_name['GetModelsResponse'] = _GETMODELSRESPONSE
DESCRIPTOR.message_types_by_name['WorkerRegistrationRequest'] = _WORKERREGISTRATIONREQUEST
DESCRIPTOR.message_types_by_name['WorkerRegistrationResponse'] = _WORKERREGISTRATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuildModelsRequest = _reflection.GeneratedProtocolMessageType('BuildModelsRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUILDMODELSREQUEST,
  '__module__' : 'modelservice_pb2'
  # @@protoc_insertion_point(class_scope:BuildModelsRequest)
  })
_sym_db.RegisterMessage(BuildModelsRequest)

BuildModelsResponse = _reflection.GeneratedProtocolMessageType('BuildModelsResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUILDMODELSRESPONSE,
  '__module__' : 'modelservice_pb2'
  # @@protoc_insertion_point(class_scope:BuildModelsResponse)
  })
_sym_db.RegisterMessage(BuildModelsResponse)

GetModelsRequest = _reflection.GeneratedProtocolMessageType('GetModelsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMODELSREQUEST,
  '__module__' : 'modelservice_pb2'
  # @@protoc_insertion_point(class_scope:GetModelsRequest)
  })
_sym_db.RegisterMessage(GetModelsRequest)

GetModelsResponse = _reflection.GeneratedProtocolMessageType('GetModelsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETMODELSRESPONSE,
  '__module__' : 'modelservice_pb2'
  # @@protoc_insertion_point(class_scope:GetModelsResponse)
  })
_sym_db.RegisterMessage(GetModelsResponse)

WorkerRegistrationRequest = _reflection.GeneratedProtocolMessageType('WorkerRegistrationRequest', (_message.Message,), {
  'DESCRIPTOR' : _WORKERREGISTRATIONREQUEST,
  '__module__' : 'modelservice_pb2'
  # @@protoc_insertion_point(class_scope:WorkerRegistrationRequest)
  })
_sym_db.RegisterMessage(WorkerRegistrationRequest)

WorkerRegistrationResponse = _reflection.GeneratedProtocolMessageType('WorkerRegistrationResponse', (_message.Message,), {
  'DESCRIPTOR' : _WORKERREGISTRATIONRESPONSE,
  '__module__' : 'modelservice_pb2'
  # @@protoc_insertion_point(class_scope:WorkerRegistrationResponse)
  })
_sym_db.RegisterMessage(WorkerRegistrationResponse)



_MASTER = _descriptor.ServiceDescriptor(
  name='Master',
  full_name='Master',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=168,
  serialized_end=446,
  methods=[
  _descriptor.MethodDescriptor(
    name='BuildModels',
    full_name='Master.BuildModels',
    index=0,
    containing_service=None,
    input_type=_BUILDMODELSREQUEST,
    output_type=_BUILDMODELSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetModels',
    full_name='Master.GetModels',
    index=1,
    containing_service=None,
    input_type=_GETMODELSREQUEST,
    output_type=_GETMODELSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterWorker',
    full_name='Master.RegisterWorker',
    index=2,
    containing_service=None,
    input_type=_WORKERREGISTRATIONREQUEST,
    output_type=_WORKERREGISTRATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeregisterWorker',
    full_name='Master.DeregisterWorker',
    index=3,
    containing_service=None,
    input_type=_WORKERREGISTRATIONREQUEST,
    output_type=_WORKERREGISTRATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTER)

DESCRIPTOR.services_by_name['Master'] = _MASTER


_WORKER = _descriptor.ServiceDescriptor(
  name='Worker',
  full_name='Worker',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=448,
  serialized_end=570,
  methods=[
  _descriptor.MethodDescriptor(
    name='BuildModels',
    full_name='Worker.BuildModels',
    index=0,
    containing_service=None,
    input_type=_BUILDMODELSREQUEST,
    output_type=_BUILDMODELSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetModels',
    full_name='Worker.GetModels',
    index=1,
    containing_service=None,
    input_type=_GETMODELSREQUEST,
    output_type=_GETMODELSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKER)

DESCRIPTOR.services_by_name['Worker'] = _WORKER

# @@protoc_insertion_point(module_scope)
